### ISSUE TITLE
Tectonic with biber fails due to biblatex incompatibility

### ISSUE THREAD

**Issue by fyndalf** [WtfJoke/setup-tectonic#194]
Hi, using the tectonic action with biber fails due to incompatibilities and produces the following error message:

```
note: Running external tool biber ...
error: the external tool exited with an error code; its stdout was:

===============================================================================
INFO - This is Biber 2.17
INFO - Logfile is 'thesis.blg'
INFO - Reading 'thesis.bcf'
ERROR - Error: Found biblatex control file version 3.7, expected version 3.8.
This means that your biber (2.17) and biblatex (3.16) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
===============================================================================
error: its stderr was:

===============================================================================
===============================================================================
error: the external tool exited with error code 2
Error: Process completed with exit code 1.
```

I have included the action similar to [the example you provided](https://github.com/WtfJoke/setup-tectonic#with-biber=), and use the "latest" version of `biber`. I don't really see a way of solving this problem, when even the latest biber version does not seem to work. Any input on this would be appreaciated! :pray:

**Comment by fyndalf** [comment]
I just realized that this obviously is a problem in relation with `tectonic` itself, see [this](https://github.com/tectonic-typesetting/tectonic/issues/893). Therefore, I'll close this issue now.

**Comment by WtfJoke** [comment]
Hey @fyndalf thanks for reporting and closing again after you found the issue upstream :)

For the time beeing, you can also try to use a previous version of tectonic which is/should be compatible with the latest biber. 

Strangely enough I wasnt able to reproduce the error in my sample repo. https://github.com/WtfJoke/setup-tectonic-sample/runs/6276270906?check_suite_focus=true

**Comment by fyndalf** [comment]
Hey @WtfJoke, using `tectonic 0.9.0` with `biber 2.16` as you suggested did indeed solve the compatibility issue for me, although I have not yet really understood why it's occurring at all. But thanks for the tip! :)

**Comment by WtfJoke** [comment]
Hey @fyndalf glad it worked :)

Forgot to answer, but AFAIK basically tectonic uses a bundle with all the tex packages (and downloads them on demand) and the bundle contains/uses a certain version of the tex package biblatex.

Biber has in its docs a [compatibility matrix, see Chapter 2.3](http://mirrors.ibiblio.org/CTAN/biblio/biber/documentation/biber.pdf), where they write with which version of biblatex they are compatible with.

So if you have an incompatibility, you either need to up/downgrade biber or up/downgrade the bundle which tectonic uses.
![grafik](https://user-images.githubusercontent.com/7139697/167673105-22f76ae0-94e4-4c45-a857-aa450c0eb449.png)

![grafik](https://user-images.githubusercontent.com/7139697/167673008-b5c74f29-29c0-441a-b873-99096762487f.png)
